name: Check JSON Schema

on:
  push:
  pull_request:

jobs:
  validate_json:
    runs-on: ["self-hosted", "k8s-prod"]
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
          node-version: 18.x
    - uses: actions/cache@v2
      name: Configure npm caching
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/validate_json.yml') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Run JSON Validation
      working-directory: ./tools
      run: |-
        npm install
        node schemaCheck.js